import {
    Calendar,
    CalendarHeart,
    CalendarMinus,
    ChartBarStacked,
    ChartColumn,
    ChartColumnDecreasing,
    ChartColumnIncreasing,
    ChartPie,
    CircleUser,
    ClipboardList,
    File,
    FileText,
    FileX,
    LayoutDashboard,
    List,
    Package,
    Plus,
    Receipt,
    Settings,
    Shield,
    ShoppingCart,
    SquareUser,
    UserCheck,
    UserCog,
    UserPlus,
    Users,
} from 'lucide-svelte';
import type { MenuItem } from './types';

export const menuList: MenuItem[] = [
    {
        name: 'Dashboard',
        type: 'file',
        icon: LayoutDashboard,
        shortcut: 'd',
        color: 'text-primary',
        url: '/admin/dashboard',
    },
    {
        name: 'Profile',
        type: 'folder',
        expanded: true,
        shortcut: 'p',
        icon: UserCog,
        color: 'text-secondary',
        children: [
            {
                name: 'Information',
                type: 'file',
                icon: CircleUser,
                color: 'text-secondary',
                shortcut: 'i',
                url: '/admin/profile/information',
            },
            {
                name: 'Schedule',
                type: 'file',
                icon: CalendarHeart,
                color: 'text-secondary',
                shortcut: 's',
                url: '/admin/profile/schedule',
            },
        ],
    },
    {
        name: 'Settings',
        type: 'folder',
        expanded: true,
        shortcut: 's',
        icon: Settings,
        color: 'text-accent',
        children: [
            {
                name: 'Role',
                type: 'folder',
                expanded: true,
                icon: Shield,
                color: 'text-accent',
                shortcut: 'r',
                children: [
                    {
                        name: 'List',
                        type: 'file',
                        icon: List,
                        color: 'text-accent',
                        url: '/admin/settings/role',
                    },
                    {
                        name: 'Create',
                        type: 'file',
                        icon: Plus,
                        color: 'text-accent',
                        shortcut: 'a',
                        url: '/admin/settings/role/create',
                    },
                ],
            },
            {
                name: 'Contact',
                type: 'folder',
                expanded: true,
                icon: UserPlus,
                color: 'text-accent',
                shortcut: 'c',
                children: [
                    {
                        name: 'List',
                        type: 'file',
                        icon: List,
                        color: 'text-accent',
                        url: '/admin/settings/contact',
                    },
                    {
                        name: 'Create',
                        type: 'file',
                        icon: UserPlus,
                        color: 'text-accent',
                        shortcut: 'a',
                        url: '/admin/settings/contact/create',
                    },
                ],
            },
            {
                name: 'Product',
                type: 'file',
                icon: Package,
                color: 'text-accent',
                shortcut: 'p',
                url: '/admin/settings/product',
            },
            {
                name: 'Calendar',
                type: 'file',
                icon: Calendar,
                color: 'text-accent',
                shortcut: 'a',
                url: '/admin/settings/calendar',
            },
        ],
    },
    {
        name: 'Purchase',
        type: 'folder',
        expanded: true,
        shortcut: 'u',
        icon: ShoppingCart,
        color: 'text-success',
        children: [
            {
                name: 'Purchase Order',
                type: 'file',
                icon: ClipboardList,
                color: 'text-success',
                shortcut: 'o',
                url: '/admin/purchase/order',
            },
            {
                name: 'Bill',
                type: 'file',
                icon: FileText,
                color: 'text-success',
                shortcut: 'b',
                url: '/admin/purchase/bill',
            },
            {
                name: 'Receipt Voucher',
                type: 'file',
                icon: Receipt,
                color: 'text-success',
                shortcut: 'r',
                url: '/admin/purchase/receipt',
            },
        ],
    },
    {
        name: 'Sales',
        type: 'folder',
        expanded: true,
        shortcut: 'a',
        icon: ChartColumn,
        color: 'text-warning',
        children: [
            {
                name: 'Quotation',
                type: 'file',
                icon: File,
                color: 'text-warning',
                shortcut: 'q',
                url: '/admin/sales/quotation',
            },
            {
                name: 'Invoice',
                type: 'file',
                icon: FileX,
                color: 'text-warning',
                shortcut: 'i',
                url: '/admin/sales/invoice',
            },
            {
                name: 'Payment Voucher',
                type: 'file',
                icon: FileText,
                color: 'text-warning',
                shortcut: 'p',
                url: '/admin/sales/payment',
            },
        ],
    },
    {
        name: 'HR',
        type: 'folder',
        expanded: true,
        shortcut: 'h',
        icon: Users,
        color: 'text-info',
        children: [
            {
                name: 'Employee',
                type: 'file',
                icon: UserCheck,
                color: 'text-info',
                shortcut: 'e',
                url: '/admin/hr/employee',
            },
            {
                name: 'Intern',
                type: 'file',
                icon: SquareUser,
                color: 'text-info',
                shortcut: 'n',
                url: '/admin/hr/intern',
            },
            {
                name: 'Leave',
                type: 'file',
                icon: CalendarMinus,
                color: 'text-info',
                shortcut: 'l',
                url: '/admin/hr/leave',
            },
        ],
    },
    {
        name: 'Report',
        type: 'folder',
        expanded: true,
        shortcut: 'r',
        icon: ChartPie,
        color: 'text-error',
        children: [
            {
                name: 'Income',
                type: 'file',
                icon: ChartColumnIncreasing,
                color: 'text-error',
                shortcut: 'i',
                url: '/admin/report/income',
            },
            {
                name: 'Expenditure',
                type: 'file',
                icon: ChartColumnDecreasing,
                color: 'text-error',
                shortcut: 'e',
                url: '/admin/report/expenditure',
            },
            {
                name: 'Sales',
                type: 'file',
                icon: ChartBarStacked,
                color: 'text-error',
                shortcut: 's',
                url: '/admin/report/sales',
            },
        ],
    },
];
